apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
      - name: flower
        image: mher/flower
        command: ["celery", "--broker=redis://redis:6379/0", "flower", "--port=5555"]
        ports:
        - containerPort: 5555
